# names of sections for menu on website
main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Lectures
    url: /lectures/
    weight: 3
  - name: Practice
    url: /practice/
    weight: 4
  - name: Assignments
    url: /assignments/
    weight: 5

# submenus left hand side of the website
lectures:
  - name: Course prep 
    weight: 1
  - name: Course introduction
    weight: 2
  - name: Descriptive statistics
    weight: 3
  - name: Bivariate descriptive statistics
    weight: 4
  - name: Graphs and tables for descriptives
    weight: 5
practice:
  - name: Course prep 
    weight: 1
  - name: Course introduction
    weight: 2
  - name: Descriptive statistics
    weight: 3
  - name: Bivariate descriptive statistics
    weight: 4
  - name: Graphs and tables for descriptives
    weight: 5
assignment:
  - name: Course prep 
    weight: 1
  - name: Course introduction
    weight: 2
  - name: Descriptive statistics
    weight: 3
  - name: Bivariate descriptive statistics
    weight: 4
  - name: Graphs and tables for descriptives
    weight: 5